INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('51', '2014-06-28 15:00:00', null, '0-0', null, '1658255', '0', 'Maracanã', '11', null, '10', '32', 'Colombia', 'Uruguay', null, null, 'COL', 'URU');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('49', '2014-06-28 11:00:00', null, '0-0', null, '1658253', '35238', 'Estádio Mineirão', '10', null, '7', '9', 'Brasil', 'Chile', null, null, 'BRA', 'CHI');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('50', '2014-06-29 11:00:00', null, '0-0', null, '1658254', '26737', 'Estádio Castelão', '12', null, '21', '27', 'Holanda', 'México', null, null, 'NED', 'MEX');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('52', '2014-06-29 15:00:00', null, '0-0', null, '1658256', '0', 'Arena Pernambuco', '13', null, '12', '20', 'Costa Rica', 'Grecia', null, null, 'CRC', 'GRE');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('53', '2014-06-30 11:00:00', null, '0-0', null, '1658257', '0', 'Estádio Nacional', '14', null, '18', '28', 'Francia', 'Nigeria', null, null, 'FRA', 'NGA');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('54', '2014-07-01 11:00:00', null, '0-0', null, '1658258', '0', 'Arena de São Paulo', '16', null, '3', '31', 'Argentina', 'Suiza', null, null, 'ARG', 'SUI');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('55', '2014-06-30 15:00:00', null, '0-0', null, '1658259', '0', 'Estádio Beira-Rio', '15', null, '1', '2', 'Alemania', 'Argelia', null, null, 'GER', 'ALG');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('56', '2014-07-01 15:00:00', null, '0-0', null, '1658260', '0', 'Arena Fonte Nova', '17', null, '5', '17', 'Bélgica', 'EEUU', null, null, 'BEL', 'USA');

INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('57', '2014-07-04 11:00:00', null, '0-0', null, '1658261', '0', 'Estadio Maracaná', '19', null, '0', '0', 'G.53', 'G.54', null, null, 'G53', 'G54');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('58', '2014-07-04 15:00:00', null, '0-0', null, '1658262', '0', 'Estádio Castelão', '20', null, '0', '0', 'G.49', 'G.50', null, null, 'G49', 'G50');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('59', '2014-07-05 11:00:00', null, '0-0', null, '1658263', '0', 'Estádio Nacional', '21', null, '0', '0', 'G.55', 'G.56', null, null, 'G55', 'G56');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('60', '2014-07-05 15:00:00', null, '0-0', null, '1658264', '0', 'Arena Fonte Nova', '22', null, '0', '0', 'G.51', 'G.52', null, null, 'G51', 'G52');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('61', '2014-07-08 15:00:00', null, '0-0', null, '1658265', '0', 'Estádio Mineirão', '23', null, '0', '0', 'G.57', 'G.58', null, null, 'G57', 'G58');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('62', '2014-07-09 15:00:00', null, '0-0', null, '1658266', '0', 'Arena de São Paulo', '24', null, '0', '0', 'G.59', 'G.60', null, null, 'G59', 'G60');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('63', '2014-07-12 15:00:00', null, '0-0', null, '1658267', '0', 'Estádio Nacional', '25', null, '0', '0', 'P.61', 'P.62', null, null, 'P61', 'P62');
INSERT INTO `partidos` (`id`, `fecha`, `estado`, `resultado`, `resumen`, `afp_id`, `afp_id_estadio`, `nombre_estadio`, `grupos_id`, `arbitro`, `local`, `visitante`, `nombre_local`, `nombre_visitante`, `tactica_local`, `tactica_visitante`, `short_name_local`, `short_name_visitante`) VALUES ('64', '2014-07-13 14:00:00', null, '0-0', null, '1658268', '0', 'Maracanã', '26', null, '0', '0', 'G.61', 'G.62', null, null, 'G61', 'G62');